on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
        image: ghcr.io/linz/action-kart:v0.1.2

    steps:
        - name: Checkout repository
          uses: actions/checkout@v6
          with:
            sparse-checkout: ".github"
            sparse-checkout-cone-mode: true

        - name: Fetch Data
          run: |
            git fetch origin ${{ github.sha }}

        - name: Prepare repo for kart clone
          run: |
            # Move .git to .kart to convert the repo in-place without re-cloning.
            mv .git .kart
            echo 'gitdir: .kart' >> .git
            git config -f .kart/config kart.repostructure.version 3
            git config -f .kart/config kart.workingcopy.location data.gpkg
            git config -f .kart/config core.repositoryformatversion 0

        - name: Export
          run: |
            for layer in $(kart data ls); do
              kart export "${layer}" "${layer}.gpkg"
            done